export const USER_LOGGED_IN = 'USER_LOGGED_IN';
export const USER_LOGGED_OUT = 'USER_LOGGED_OUT';
export const CONTACTS_FETCHED = 'CONTACTS_FETCHED';
export const CONTACT_CREATED = 'CONTACT_CREATED';
export const CONTACT_DELETED = 'CONTACT_DELETED';